### ISSUE TITLE
Idea: go-thrust command

### ISSUE THREAD

**Issue by francisbouvier** [miketheprogrammer/go-thrust#45]
Hi,

As far as I understand, the Thrust executable is downloaded at first launch.

I think it will be better to have it downloaded at installation, like the pythrust binding do.
Unfortunately there is no equivalent of `setup.py` in go, so maybe the solution is to have a `go-thrust` command to handle this.

Instructions to install go-thrust will be:
```sh
go get github.com/miketheprogrammer/go-thrust 
# Install the go-thrust cmd and lib

go-thrust install
# Install the Thrust executable
```
If you think it's a good idea I can write the tool.

**Comment by jsanc623** [comment]
I like this idea - an extra command during installation shouldn't be much of a nuisance IMHO

**Comment by miketheprogrammer** [comment]
Yes, feel free to submit a pull request. We discussed this earlier, but the project owner of Thrust was hoping to have all *-Thrust packages install at runtime.

Currently you can change the provisioner, so that in end user applications this behavior does not happen and instead uses a packaged thrust executable.

I give my approval, and I see others like the Idea, so lets do it. 

We will however keep the defaultprovisioner in the case that the user does not opt to use go-thrust install
i.e. backwards compat.

**Comment by miketheprogrammer** [comment]
Closing this as the PR has been merged
