### ISSUE TITLE
setup instructions need work

### ISSUE THREAD

**Issue by taf2** [miketheprogrammer/go-thrust#51]
go version go1.4.2 darwin/amd64

go get  github.com/miketheprogrammer/go-thrust
can't load package: package github.com/miketheprogrammer/go-thrust: no buildable Go source files in /Users/taf2/work/golibs/src/github.com/miketheprogrammer/go-thrust

go get -v github.com/alexcesaro/log
github.com/alexcesaro/log

go-thrust install
bash: go-thrust: command not found

**Comment by miketheprogrammer** [comment]
Did you ever get this working?

**Comment by taf2** [comment]
Yes, I checked the code out and was able to run go build to create the go-thrust binary.    The README is incorrect though right?

**Comment by sharpner** [comment]
the problem is that you're missing $GOPATH/bin in your $PATH environment variable. https://golang.org/cmd/go/#hdr-GOPATH_environment_variable

**Comment by tehbilly** [comment]
`can't load package: package github.com/miketheprogrammer/go-thrust: no buildable Go source files in ...`

This doesn't point to a path issue, but more that for some reason go wasn't able to find anything in `$GOPATH/src/github.com/miketheprogrammer/go-thrust`. I've had this happen due to network issues, filesystem issues, whatever. I always recommend people use the `-v ` flag to see what's going on.

Either way, I'd say this issue is resolved, as without more information it's pretty impossible to determine what caused that in the first place.
